[package]
name = "vls"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0.141"
ve = { git = "https://github.com/veil-lang/veil.git", branch = "main" }
codespan = "0.11.1"
codespan-reporting = "0.11.0"
url = "2.5.4"